# Generated by Buildr 1.4.3, change to your liking
# Version number for this release
VERSION_NUMBER = "0.0.1"
# Group identifier for your projects
GROUP = "monstrous"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://www.ibiblio.org/maven2/"

require 'buildfile_libraries'

JARS = artifacts([ HTTPCLIENT, JSON_LIB ].flatten.uniq)

desc "The Monstrous project"
define "monstrous" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
  
  eclipse.natures :java
  
  compile.with JARS
  
  package(:jar)
  package(:jar).enhance { |pkg| pkg.enhance { |pkg| add_dependencies(pkg) }}
  
end
